export const data_itens = [
  // Micro-verdes
  {
    id: 1001,
    name: 'Micro-verde de Rabanete',
    pic: '',
    description: 'Micro-verde com crescimento rápido, pronto em poucos dias.',
    category: 'Micro-verde',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Naturais',
    season: ['Primavera', 'Outono'],
    life: 10,
    measure: 'KG',
    price: 15.5
  },
  {
    id: 1002,
    name: 'Micro-verde de Mostarda',
    pic: '',
    description: 'Micro-verde de sabor picante, ideal para saladas.',
    category: 'Micro-verde',
    group: 'Peletizada',
    manufacturer: 'Cultivo Verde',
    season: ['Primavera', 'Outono'],
    life: 12,
    measure: 'KG',
    price: 18.2
  },
  {
    id: 1003,
    name: 'Micro-verde de Manjericão',
    pic: '',
    description: 'Aromático e fresco, ótimo para temperos.',
    category: 'Micro-verde',
    group: 'Sem peletização',
    manufacturer: 'Verde Perfeito',
    season: ['Verão', 'Outono'],
    life: 15,
    measure: 'KG',
    price: 20.0
  },
  {
    id: 1004,
    name: 'Micro-verde de Girassol',
    pic: '',
    description: 'Rico em nutrientes, ideal para consumo diário.',
    category: 'Micro-verde',
    group: 'Peletizada',
    manufacturer: 'Hortaliças Naturais',
    season: ['Primavera', 'Verão'],
    life: 8,
    measure: 'KG',
    price: 12.7
  },
  {
    id: 1005,
    name: 'Micro-verde de Beterraba',
    pic: '',
    description: 'Com um toque doce, combina com várias receitas.',
    category: 'Micro-verde',
    group: 'Sem peletização',
    manufacturer: 'Cultivo Verde',
    season: ['Primavera', 'Outono'],
    life: 14,
    measure: 'KG',
    price: 16.3
  },
  
  // Legumes
  {
    id: 2001,
    name: 'Cenoura',
    pic: '',
    description: 'Legume rico em vitamina A, ótimo para saladas.',
    category: 'Legume',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Naturais',
    season: ['Outono', 'Inverno'],
    life: 30,
    measure: 'KG',
    price: 4.0
  },
  {
    id: 2002,
    name: 'Pepino',
    pic: '',
    description: 'Legume fresco e crocante, excelente para saladas.',
    category: 'Legume',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Naturais',
    season: ['Verão', 'Outono'],
    life: 20,
    measure: 'KG',
    price: 3.2
  },
  {
    id: 2003,
    name: 'Tomate',
    pic: '',
    description: 'Fruto utilizado como legume, ideal para molhos.',
    category: 'Legume',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Tropicais',
    season: ['Primavera', 'Verão'],
    life: 10,
    measure: 'KG',
    price: 7.4
  },
  {
    id: 2004,
    name: 'Abobrinha',
    pic: '',
    description: 'Legume versátil, ótimo para grelhar ou cozinhar.',
    category: 'Legume',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Naturais',
    season: ['Primavera', 'Verão'],
    life: 15,
    measure: 'KG',
    price: 5.3
  },
  {
    id: 2005,
    name: 'Batata',
    pic: '',
    description: 'Legume essencial para várias receitas.',
    category: 'Legume',
    group: 'Sem peletização',
    manufacturer: 'Hortaliças Tropicais',
    season: ['Outono', 'Inverno'],
    life: 30,
    measure: 'KG',
    price: 3.8
  },

  // Temperos
  {
    id: 3001,
    name: 'Manjericão',
    pic: '',
    description: 'Fresco e aromático, excelente para molhos e pizzas.',
    category: 'Tempero',
    group: 'Sem peletização',
    manufacturer: 'Ervas Aromáticas',
    season: ['Verão', 'Outono'],
    life: 60,
    measure: 'Un',
    price: 5.2
  },
  {
    id: 3002,
    name: 'Alecrim',
    pic: '',
    description: 'Sabor marcante, ideal para carnes e pães.',
    category: 'Tempero',
    group: 'Sem peletização',
    manufacturer: 'Ervas Aromáticas',
    season: ['Primavera', 'Outono'],
    life: 70,
    measure: 'Un',
    price: 6.8
  },
  {
    id: 3003,
    name: 'Salsa',
    pic: '',
    description: 'Versátil e fresca, perfeita para diversas receitas.',
    category: 'Tempero',
    group: 'Peletizada',
    manufacturer: 'Hortaliças Naturais',
    season: ['Primavera', 'Verão'],
    life: 50,
    measure: 'Un',
    price: 4.5
  },
  {
    id: 3004,
    name: 'Cebolinha',
    pic: '',
    description: 'Suave e aromática, para finalizar pratos.',
    category: 'Tempero',
    group: 'Sem peletização',
    manufacturer: 'Cultivo Verde',
    season: ['Primavera', 'Outono'],
    life: 55,
    measure: 'Un',
    price: 3.9
  },
  {
    id: 3005,
    name: 'Tomilho',
    pic: '',
    description: 'Aroma intenso, ótimo para marinadas.',
    category: 'Tempero',
    group: 'Sem peletização',
    manufacturer: 'Ervas Aromáticas',
    season: ['Primavera', 'Outono'],
    life: 75,
    measure: 'Un',
    price: 7.1
  },

  // Frutas
  {
    id: 4001,
    name: 'Maçã Fuji',
    pic: '',
    description: 'Fruta doce e crocante, ideal para lanches.',
    category: 'Fruta',
    group: 'Sem peletização',
    manufacturer: 'Frutas do Campo',
    season: ['Outono', 'Inverno'],
    life: 30,
    measure: 'Un',
    price: 4.3
  },
  {
    id: 4002,
    name: 'Laranja Pera',
    pic: '',
    description: 'Suculenta e rica em vitamina C.',
    category: 'Fruta',
    group: 'Sem peletização',
    manufacturer: 'Frutas do Campo',
    season: ['Inverno', 'Primavera'],
    life: 20,
    measure: 'Un',
    price: 2.1
  },
  {
    id: 4003,
    name: 'Banana Prata',
    pic: '',
    description: 'Fruta doce e macia, perfeita para sobremesas.',
    category: 'Fruta',
    group: 'Sem peletização',
    manufacturer: 'Frutas Tropicais',
    season: ['Verão', 'Outono'],
    life: 15,
    measure: 'Un',
    price: 3.4
  },
  {
    id: 4004,
    name: 'Morango',
    pic: '',
    description: 'Fruta vermelha e doce, ótima para sobremesas.',
    category: 'Fruta',
    group: 'Sem peletização',
    manufacturer: 'Frutas do Campo',
    season: ['Primavera', 'Verão'],
    life: 7,
    measure: 'Un',
    price: 6.5
  },
  {
    id: 4005,
    name: 'Uva Itália',
    pic: '',
    description: 'Uva doce e sem sementes, ideal para consumo direto.',
    category: 'Fruta',
    group: 'Sem peletização',
    manufacturer: 'Frutas Tropicais',
    season: ['Verão', 'Outono'],
    life: 10,
    measure: 'Un',
    price: 12.3
  },

  // Flores
  {
    id: 5001,
    name: 'Capuchinha',
    pic: '',
    description: 'Flor comestível com sabor picante, excelente para saladas e pratos decorativos.',
    category: 'Flor',
    group: 'Sem peletização',
    manufacturer: 'Flores do Jardim',
    season: ['Primavera', 'Verão'],
    life: 5,
    measure: 'Un',
    price: 8.0
  },
  {
    id: 5002,
    name: 'Lavanda',
    pic: '',
    description: 'Flor com aroma agradável, usada em chás, sobremesas e pratos de carne.',
    category: 'Flor',
    group: 'Sem peletização',
    manufacturer: 'Flores do Jardim',
    season: ['Primavera', 'Verão'],
    life: 6,
    measure: 'Un',
    price: 10.2
  },
  {
    id: 5003,
    name: 'Amor-perfeito',
    pic: '',
    description: 'Flor doce e delicada, utilizada em saladas, sobremesas e como guarnição.',
    category: 'Flor',
    group: 'Sem peletização',
    manufacturer: 'Flores do Jardim',
    season: ['Outono', 'Primavera'],
    life: 4,
    measure: 'Un',
    price: 5.5
  },
  {
    id: 5004,
    name: 'Flor de abóbora',
    pic: '',
    description: 'Flor comestível que pode ser recheada ou usada em sopas e saladas.',
    category: 'Flor',
    group: 'Sem peletização',
    manufacturer: 'Flores comestíveis',
    season: ['Primavera', 'Verão'],
    life: 7,
    measure: 'Un',
    price: 12.0
  },
  {
    id: 5005,
    name: 'Hibisco',
    pic: '',
    description: 'Flor usada em chás e sobremesas, com sabor agridoce.',
    category: 'Flor',
    group: 'Sem peletização',
    manufacturer: 'Flores comestíveis',
    season: ['Primavera', 'Verão'],
    life: 5,
    measure: 'Un',
    price: 6.5
  }
]
